### ISSUE TITLE
 Use h.SharedInformerFactory() to get  SharedInformerFactory ,  AddIndexers Error

### ISSUE THREAD

**Issue by shenkonghui** [kubernetes-sigs/scheduler-plugins#251]
when I use h.SharedInformerFactory() to get schedSharedInformerFactory. It will panic
```
	schedSharedInformerFactory := h.SharedInformerFactory()
	podInformer := schedSharedInformerFactory.Core().V1().Pods()

	podInformer.Informer().AddIndexers(cache.Indexers{
		"xxx": func(obj interface{}) ([]string, error) {
			pod, ok := obj.(*v1.Pod)
			if ok {
			}
			return []string{}, nil
		},
	})
```
```
I0907 19:57:35.866691   63488 serving.go:331] Generated self-signed cert in-memory
W0907 19:57:36.097360   63488 authentication.go:307] No authentication-kubeconfig provided in order to lookup client-ca-file in configmap/extension-apiserver-authentication in kube-system, so client certificate authentication won't work.
W0907 19:57:36.097375   63488 authentication.go:331] No authentication-kubeconfig provided in order to lookup requestheader-client-ca-file in configmap/extension-apiserver-authentication in kube-system, so request-header client certificate authentication won't work.
W0907 19:57:36.097387   63488 authorization.go:176] No authorization-kubeconfig provided, so SubjectAccessReview of authorization tokens won't work.
panic: assignment to entry in nil map

goroutine 1 [running]:
k8s.io/client-go/tools/cache.(*threadSafeMap).AddIndexers(0xc000173590, 0xc000432ba0, 0x0, 0x0)
        /Users/shenkonghui/src/work/scheduler-plugins/vendor/k8s.io/client-go/tools/cache/thread_safe_store.go:249 +0x1b3
k8s.io/client-go/tools/cache.(*cache).AddIndexers(0xc00000e3d8, 0xc000432ba0, 0x377835d7aa013801, 0xc0004b0d00)
        /Users/shenkonghui/src/work/scheduler-plugins/vendor/k8s.io/client-go/tools/cache/store.go:211 +0x3d
k8s.io/client-go/tools/cache.(*sharedIndexInformer).AddIndexers(0xc000568500, 0xc000432ba0, 0x0, 0x0)
        /Users/shenkonghui/src/work/scheduler-plugins/vendor/k8s.io/client-go/tools/cache/shared_informer.go:449 +0xea
sigs.k8s.io/scheduler-plugins/pkg/podNumlimit.New(0x0, 0x0, 0x2c357e8, 0xc0001b2ea0, 0x0, 0x0, 0x0, 0x0)
        /Users/shenkonghui/src/work/scheduler-plugins/pkg/podNumlimit/podNumlimit.go:84 +0x1ea
k8s.io/kubernetes/pkg/scheduler/framework/runtime.NewFramework(0xc000173770, 0xc00030ca80, 0x0, 0x0, 0x0, 0xc00030cc60, 0x8, 0xc, 0xc0005c1401, 0xc000591590, ...)
        /Users/shenkonghui/src/work/scheduler-plugins/vendor/k8s.io/kubernetes/pkg/scheduler/framework/runtime/framework.go:297 +0x86b
k8s.io/kubernetes/pkg/scheduler/profile.newProfile(0xc000337158, 0x14, 0xc00030ca80, 0x0, 0x0, 0x0, 0xc000173770, 0xc00042ca00, 0xc0005c17a0, 0x6, ...)
        /Users/shenkonghui/src/work/scheduler-plugins/vendor/k8s.io/kubernetes/pkg/scheduler/profile/profile.go:41 +0x12c
k8s.io/kubernetes/pkg/scheduler/profile.NewMap(0xc0001737d0, 0x1, 0x1, 0xc000173770, 0xc00042ca00, 0xc0005c17a0, 0x6, 0x6, 0xc0005c1600, 0xb46b810, ...)
        /Users/shenkonghui/src/work/scheduler-plugins/vendor/k8s.io/kubernetes/pkg/scheduler/profile/profile.go:61 +0x185
k8s.io/kubernetes/pkg/scheduler.(*Configurator).create(0xc0005c1a98, 0xc000284420, 0x298e978, 0xf)
        /Users/shenkonghui/src/work/scheduler-plugins/vendor/k8s.io/kubernetes/pkg/scheduler/factory.go:135 +0xbf5
k8s.io/kubernetes/pkg/scheduler.(*Configurator).createFromProvider(0xc0005c1a98, 0x298e978, 0xf, 0xc000432930, 0x1, 0x1)
        /Users/shenkonghui/src/work/scheduler-plugins/vendor/k8s.io/kubernetes/pkg/scheduler/factory.go:201 +0x25d
k8s.io/kubernetes/pkg/scheduler.New(0x2c491d0, 0xc0000dc2c0, 0x2c450a8, 0xc0000b0b40, 0xc00042ca00, 0xc000058e40, 0xc0005c1c28, 0x9, 0x9, 0xc0005c37e0, ...)
        /Users/shenkonghui/src/work/scheduler-plugins/vendor/k8s.io/kubernetes/pkg/scheduler/scheduler.go:237 +0x78c
k8s.io/kubernetes/cmd/kube-scheduler/app.Setup(0x2c22c10, 0xc0005d8dc0, 0xc0008a2340, 0xc00000e6f0, 0x3, 0x3, 0x47, 0x47, 0x47, 0x46)
        /Users/shenkonghui/src/work/scheduler-plugins/vendor/k8s.io/kubernetes/cmd/kube-scheduler/app/server.go:322 +0x4fb
k8s.io/kubernetes/cmd/kube-scheduler/app.runCommand(0xc0005d1080, 0xc0008a2340, 0xc00000e6f0, 0x3, 0x3, 0x0, 0x0)
        /Users/shenkonghui/src/work/scheduler-plugins/vendor/k8s.io/kubernetes/cmd/kube-scheduler/app/server.go:127 +0xea
k8s.io/kubernetes/cmd/kube-scheduler/app.NewSchedulerCommand.func1(0xc0005d1080, 0xc0005f2660, 0x0, 0x3)
        /Users/shenkonghui/src/work/scheduler-plugins/vendor/k8s.io/kubernetes/cmd/kube-scheduler/app/server.go:81 +0x53
github.com/spf13/cobra.(*Command).execute(0xc0005d1080, 0xc00004e0d0, 0x3, 0x3, 0xc0005d1080, 0xc00004e0d0)
        /Users/shenkonghui/src/work/scheduler-plugins/vendor/github.com/spf13/cobra/command.go:854 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc0005d1080, 0x3, 0x3, 0xc0005d1080)
        /Users/shenkonghui/src/work/scheduler-plugins/vendor/github.com/spf13/cobra/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/shenkonghui/src/work/scheduler-plugins/vendor/github.com/spf13/cobra/command.go:895
main.main()
        /Users/shenkonghui/src/work/scheduler-plugins/cmd/scheduler/main.go:63 +0x1c9

```

If I use informers.NewSharedInformerFactory(h.ClientSet(), time.Second*30), It will be ok.
```
	schedSharedInformerFactory := informers.NewSharedInformerFactory(h.ClientSet(), time.Second*30)
	podInformer := schedSharedInformerFactory.Core().V1().Pods()

	podInformer.Informer().AddIndexers(cache.Indexers{
		"xxx": func(obj interface{}) ([]string, error) {
			pod, ok := obj.(*v1.Pod)
			if ok {
			}
			return []string{}, nil
		},
	})
```

**Comment by Huang-Wei** [comment]
> 	schedSharedInformerFactory := informers.NewSharedInformerFactory(h.ClientSet(), time.Second*30)

It seems you're vendoring k8s 1.22. Is the panic coming from `h.ClientSet()`? In other words, could you show me the code repo where the error was found:

```
sigs.k8s.io/scheduler-plugins/pkg/podNumlimit.New(0x0, 0x0, 0x2c357e8, 0xc0001b2ea0, 0x0, 0x0, 0x0, 0x0)
        /Users/shenkonghui/src/work/scheduler-plugins/pkg/podNumlimit/podNumlimit.go:84 +0x1ea
```
